accepted = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "GPL-3.0",
  "ISC",
  "LicenseRef-UFL-1.0",
  "MIT",
  "MPL-2.0",
  "OFL-1.1",
  "OpenSSL",
  "Unicode-DFS-2016",
  "Zlib",
]

workarounds = ["ring"]


[webpki.clarify]
license = "ISC"

[[webpki.clarify.files]]
path = "LICENSE"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"